version: '3'
services:
  database:
    container_name: database
    image: postgres:10.7
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
# sudo docker-compose -f docker-compose.yml up --build -d database
